#include "emg.h"

/* actual page data offsets */
#define MANGAREADER_SEARCH_INDEX 12830 /* off by 2 for some reason, but it works */
#define MANGAREADER_SEARCH_INDEX_NAME_COUNT 1
#define MANGAREADER_SEARCH_INDEX_START 145
#define MANGAREADER_SEARCH_INDEX_START_CHAR '\''
#define MANGAREADER_SEARCH_INDEX_POST_IMAGE 83
#define MANGAREADER_SEARCH_INDEX_POST_IMAGE_CHAR '"'
#define MANGAREADER_SEARCH_INDEX_POST_HREF 2
#define MANGAREADER_SEARCH_INDEX_POST_HREF_CHAR '<'
#define MANGAREADER_SEARCH_INDEX_CHAP 51
#define MANGAREADER_SEARCH_INDEX_CHAP_CHAR '<'
#define MANGAREADER_SEARCH_INDEX_TAGS 88
#define MANGAREADER_SEARCH_INDEX_TAGS_CHAR '<'
#define MANGAREADER_SEARCH_INDEX_END 54
#define MANGAREADER_SEARCH_INDEX_END_CHAR 0
#define MANGAREADER_DATA_CB (Provider_Data_Cb)mangareader_search_name_cb
#define MANGAREADER_INIT_CB (Provider_Init_Cb)mangareader_series_init_cb

#define MANGAREADER_SERIES_INDEX 2807
#define MANGAREADER_SERIES_INDEX_NAME_COUNT 8
#define MANGAREADER_SERIES_INDEX_START 0
#define MANGAREADER_SERIES_INDEX_START_CHAR '"'
#define MANGAREADER_SERIES_INDEX_POST_IMAGE 214
#define MANGAREADER_SERIES_INDEX_POST_IMAGE_NAME_COUNT 3
#define MANGAREADER_SERIES_INDEX_POST_IMAGE_CHAR '<'
#define MANGAREADER_SERIES_INDEX_ALT_NAME 69
#define MANGAREADER_SERIES_INDEX_ALT_NAME_CHAR '<'
#define MANGAREADER_SERIES_INDEX_YEAR 60
#define MANGAREADER_SERIES_INDEX_YEAR_CHAR '<'
#define MANGAREADER_SERIES_INDEX_COMPLETED 60
#define MANGAREADER_SERIES_INDEX_COMPLETED_CHAR '<'
#define MANGAREADER_SERIES_INDEX_AUTHOR 60
#define MANGAREADER_SERIES_INDEX_AUTHOR_CHAR '<'
#define MANGAREADER_SERIES_INDEX_ARTIST 60
#define MANGAREADER_SERIES_INDEX_ARTIST_CHAR '<'
#define MANGAREADER_SERIES_INDEX_JUMP 67
#define MANGAREADER_SERIES_INDEX_JUMP_CHAR 0

#define MANGAREADER_PAGE_INDEX 1719
#define MANGAREADER_PAGE_INDEX_NAME_COUNT 10
#define MANGAREADER_PAGE_INDEX_START 0
#define MANGAREADER_PAGE_INDEX_START_CHAR ']'
#define MANGAREADER_PAGE_INDEX_JUMP 24
#define MANGAREADER_PAGE_INDEX_JUMP_CHAR ']'
#define MANGAREADER_PAGE_INDEX_NEXT 5
#define MANGAREADER_PAGE_INDEX_NEXT_CHAR '\''
#define MANGAREADER_PAGE_INDEX_PREV 25
#define MANGAREADER_PAGE_INDEX_PREV_CHAR '\''
#define MANGAREADER_PAGE_INDEX_IMG 25
#define MANGAREADER_PAGE_INDEX_IMG_CHAR '\''

#define MANGAREADER_SEARCH_URL "http://www.mangareader.net/search/?w="
#define MANGAREADER_URL "http://www.mangareader.net"

#define MANGAREADER_SEARCH_SETUP(SN) \
do { \
   PROVIDER_SEARCH_SETUP((SN), MANGAREADER); \
} while (0)
